## Abstract

Social media platforms have altered the ways that we communicate. The tremendous volumes of streaming data that are available through platforms like Twitter and Facebook enable the investigation of new data science research questions. In many cases, these research questions may motivate engaging, accessible, and scientifically meaningful studies for those who are new to data science research. 
In seeking to explore social media data science as a pedagogical tool, we guided two undergraduate researchers while they completed research projects. After discussing the nature of downloaded Twitter data, we encouraged the students to formulate novel research questions that both draw on the time series structure of tweets and complement students' existing data science interests. One student elected to study relationships over time between tweet sentiments and stock market index values. The other chose to develop unsupervised methods to detect social media events, like the occurrence of the Super Bowl football game. Both students prepared manuscripts and posters to document their methods and findings. We found that research skills, self-confidence in research ability, and professional interest in data science increased for both students. 
