# Introduction

The need to analyze unprecedentedly large volumes of information combined with 
the development of faster and more powerful computers has fueled advances in 
data science methods for big data. Similar causes have led to a
need for greater 
numbers of scientists with quantitative skills. In efforts to enhance training
and mentoring for students, we created a program that emphasizes many 
transferable skills that contribute to career success in data science.

We elected to work with social media data. In making 
this decision, we recognized that social media data, such as tweets from 
Twitter, can be acquired with little cost and that there is growing research 
interest in social media in many social science disciplines, including political 
science, communication studies, and sociology. We also anticipated 
that our undergraduate trainees might be intrigued by the possibility of 
analyzing social media data, since many young adults use Facebook, Twitter, 
Instagram, and related sites.


Some social media data, including tweets from Twitter, are 
available through website application product interfaces (APIs). Twitter 
shares, via a streaming API, a sample of approximately one percent of all 
tweets during an API query time period [@tweet_stream].
Researchers have studied tweets for a 
variety of purposes, including 
inference of relationships and social networks among users [@lin2011joint]; 
determination of 
authorship of specific tweets when multiple persons share a single account [@drob]; and 
study of rhetoric in recruiting political supporters [@pelled2018little;@wells2016trump].
Recognizing the potential utility of tweets for data science research and teaching, 
we created a 
collection of tweets over time by repeated querying of the Twitter streaming API.

@nolan2010computing argue for students to work with real data. 
Working with real data allows students to develop skill not only in statistical analysis,
but also in data transfer from online sources, in data storage, and in using data 
from multiple file formats. In the case of Twitter data, tweets are stored in
Javascript Object Notation (JSON) [@tweet_json;@json]. 

Mentoring in the work place and in higher education can have many 
benefits, including improving students' development as thinkers and scholars, confidence in their 
own abilities, integration into the campus community,
and interest in graduate training 
[@baker2010beyond;@higgins2001reconceptualizing].
A key component of our data science mentoring framework is 
the emphasis on using real data to answer 
scientific questions. We believe that this process develops problem-solving skills that 
students will need in their future careers in data science. 
We encouraged students to articulate a scientific research question, translate that question 
into quantitative and statistical terms, determine which data could be used to address the 
question, acquire the data, analyze data, visualize results, and communicate what they learned.



## Our backgrounds

During the time when we first implemented our framework, we served as early-career instructors in 
the statistics department at the University of Wisconsin-Madison. One of us (Hanlon) had prior 
experience in mentoring students, while the other (Boehm) had none. Our initial 
conceptualization of mentoring drew heavily on ideas we first encountered in professional 
development 
activities, including the Delta Program's mentoring class (https://delta.wisc.edu) and @handelsman2005entering. 
Professor Erik Nordheim's class, "Teaching Statistics", 
influenced our approach to and philosophy of teaching statistics. 
We studied with Professor Nordheim early in our teaching 
careers, and his course's emphasis on backward design and active learning continues to influence our teaching practices (https://delta.wisc.edu). 

We both have experience in teaching undergraduate introductory 
statistics courses with enrollments of more than 
100 students. Through our interactions with students in these 
classes, we've grown to value not only 
the ideas in a traditional introductory course, but also the need 
to prepare students with the essential skills needed for success 
in data science. @nolan2010computing summarizes these skill sets 
in the following three goals:

1. broaden statistical computing to include emerging areas
1. deepen computational reasoning skills
1. combine computational topics with data analysis in the practice of statistics

To these three praiseworthy goals, we add a fourth:

4. develop skills in reproducible research to promote open science practices

We see the fourth goal as an equal with the first three from @nolan2010computing. 
Data scientists are uniquely positioned to promote open science 
practices, including the free sharing of 
data, code, and instructions for their use. 
The need for science to be more transparent and more reproducible
elevate this goal to the level of the first three.

Below, we detail our methods for creating a reproducible framework
for undergraduate data science 
research. We describe our results before concluding with lessons learned, 
things we could have done differently, and recommendations for future 
mentors who may use and extend our framework. 


