---
title: "Notes on @nolan2010computing"
author: "Frederick J. Boehm"
date: "10/25/2019"
output: html_document
bibliography: jse.bib
---

> The main message of this article is that the digital age is having a profound impact on statistics and the nature of data analysis, and these changes necessitate reevaluation of the training and education practices in statistics.

> Successful statisticians must be facile with the computer, for they are expected to be able to access data from various sources, apply the latest statistical methodologies, and communicate their findings to others in novel ways and via new media.

> When they graduate, what ought our students be able to do computationally, and are we preparing them adequately in this regard?

> Do we provide students the essential skills needed to engage in statistical problem solving and keep abreast of new technologies as they evolve?

> Do our students build the confidence needed to overcome computational challenges to, for example, reliably design and run a synthetic experiment or carry out a comprehensive data analysis?

> Overall, are we doing a good job preparing students who are ready to engage in and succeed at statistical inquiry?


@nolan2010computing identify "three key aspects":

1. broaden statistical computing to include emerging areas
1. deepen computational reasoning skills
1. combine computational topics with data analysis in the practice of statistics


